# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# AMaPOTrainer arguments
bf16: true
beta: 2.0
length_norm: true
do_eval: true
evaluation_strategy: steps
eval_steps: 1000
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: AMaPO-exps
learning_rate: 4.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/Zephyr-7b-base-AMaPO
run_name: Zephyr-7b-base-AMaPO
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "steps"
save_steps: 1000
report_to:
- wandb
save_total_limit: 10
seed: 42
warmup_ratio: 0.1